-- Ejecutar una vez en el SQL Editor de Supabase.
-- Políticas editables para préstamos físicos.
create table if not exists public.politicas_prestamo (
  id smallint primary key default 1 check (id = 1),
  dias_prestamo integer not null default 7 check (dias_prestamo between 1 and 60),
  max_renovaciones integer not null default 2 check (max_renovaciones between 0 and 10),
  dias_tolerancia integer not null default 0 check (dias_tolerancia between 0 and 30),
  max_libros_por_usuario integer not null default 3 check (max_libros_por_usuario between 1 and 20),
  horas_retiro_reserva integer not null default 48 check (horas_retiro_reserva between 1 and 336),
  updated_at timestamptz not null default now()
);
insert into public.politicas_prestamo (id) values (1) on conflict (id) do nothing;

create table if not exists public.renovaciones_prestamo (
  id_renovacion bigint generated by default as identity primary key,
  id_prestamo bigint not null references public.prestamos(id_prestamo) on delete cascade,
  fecha_renovacion date not null default current_date,
  fecha_limite_anterior date not null,
  fecha_limite_nueva date not null,
  observacion text
);

alter table public.politicas_prestamo enable row level security;
alter table public.renovaciones_prestamo enable row level security;

drop policy if exists "admin gestiona politicas de prestamo" on public.politicas_prestamo;
create policy "admin gestiona politicas de prestamo" on public.politicas_prestamo for all using (
  exists (select 1 from public.usuarios where id_rol = 1 and lower(email) = lower(auth.jwt() ->> 'email'))
) with check (
  exists (select 1 from public.usuarios where id_rol = 1 and lower(email) = lower(auth.jwt() ->> 'email'))
);
drop policy if exists "admin gestiona renovaciones" on public.renovaciones_prestamo;
create policy "admin gestiona renovaciones" on public.renovaciones_prestamo for all using (
  exists (select 1 from public.usuarios where id_rol = 1 and lower(email) = lower(auth.jwt() ->> 'email'))
) with check (
  exists (select 1 from public.usuarios where id_rol = 1 and lower(email) = lower(auth.jwt() ->> 'email'))
);
