-- Ejecutar una sola vez en el SQL Editor de Supabase si estas tablas aún no existen.
-- No modifica ninguna tabla ni conexión existente.
create table if not exists public.valoraciones (
  id_valoracion bigint generated by default as identity primary key,
  id_libro bigint not null references public.libros(id_libro) on delete cascade,
  id_usuario bigint not null references public.usuarios(id_usuario) on delete cascade,
  puntuacion smallint not null check (puntuacion between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_libro, id_usuario)
);
create table if not exists public.sanciones (
  id_sancion bigint generated by default as identity primary key,
  id_prestamo bigint not null references public.prestamos(id_prestamo) on delete cascade,
  id_usuario bigint not null references public.usuarios(id_usuario) on delete cascade,
  motivo text not null,
  monto numeric(10,2),
  estado text not null default 'Pendiente',
  fecha_sancion date not null default current_date
);
-- Seguridad: asume que usuarios.email coincide con el correo de Supabase Auth.
-- Los administradores se reconocen por usuarios.id_rol = 1.
alter table public.valoraciones enable row level security;
alter table public.sanciones enable row level security;
drop policy if exists "lectura publica de valoraciones" on public.valoraciones;
drop policy if exists "usuarios califican con su perfil" on public.valoraciones;
drop policy if exists "usuarios actualizan su valoracion" on public.valoraciones;
drop policy if exists "lectura de sanciones" on public.sanciones;
drop policy if exists "gestion de sanciones" on public.sanciones;
create policy "lectura de valoraciones" on public.valoraciones for select using (true);
create policy "usuarios califican con su perfil" on public.valoraciones for insert with check (
  exists (select 1 from public.usuarios u where u.id_usuario = public.valoraciones.id_usuario and lower(u.email) = lower(auth.jwt() ->> 'email'))
);
create policy "usuarios actualizan su valoracion" on public.valoraciones for update using (
  exists (select 1 from public.usuarios u where u.id_usuario = public.valoraciones.id_usuario and lower(u.email) = lower(auth.jwt() ->> 'email'))
) with check (
  exists (select 1 from public.usuarios u where u.id_usuario = public.valoraciones.id_usuario and lower(u.email) = lower(auth.jwt() ->> 'email'))
);
create policy "administradores gestionan sanciones" on public.sanciones for all using (
  exists (select 1 from public.usuarios u where u.id_rol = 1 and lower(u.email) = lower(auth.jwt() ->> 'email'))
) with check (
  exists (select 1 from public.usuarios u where u.id_rol = 1 and lower(u.email) = lower(auth.jwt() ->> 'email'))
);
