-- Ejecutar una vez en el SQL Editor de Supabase.
create table if not exists public.biblioteca_personal (
  id_biblioteca_personal bigint generated by default as identity primary key,
  id_usuario bigint not null references public.usuarios(id_usuario) on delete cascade,
  id_libro bigint not null references public.libros(id_libro) on delete cascade,
  estado text not null check (estado in ('Leer después', 'Leyendo', 'Finalizado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_usuario, id_libro)
);

alter table public.biblioteca_personal enable row level security;
create policy "usuarios leen su biblioteca personal" on public.biblioteca_personal for select using (
  exists (select 1 from public.usuarios u where u.id_usuario = public.biblioteca_personal.id_usuario and lower(u.email) = lower(auth.jwt() ->> 'email'))
);
create policy "usuarios gestionan su biblioteca personal" on public.biblioteca_personal for all using (
  exists (select 1 from public.usuarios u where u.id_usuario = public.biblioteca_personal.id_usuario and lower(u.email) = lower(auth.jwt() ->> 'email'))
) with check (
  exists (select 1 from public.usuarios u where u.id_usuario = public.biblioteca_personal.id_usuario and lower(u.email) = lower(auth.jwt() ->> 'email'))
);
